<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <div style="display: flex;">
        <div style="flex: 1; text-align: right; margin-right: 10px;">
            version :<br/>
            date : <br/>
            auteur :<br/>
            courriel :<br/>
            licence :<br/>
        </div>
        <div style="flex: 2; margin-right: 10px;">
            2.0<br/>
            26 janvier 2024<br/>
            Camille-Aimé Possamaï<br/>
            c.pos@orange.fr<br/>
            <span style="font-style: italic;">GNU General Public Licence (v3.0)</span>
        </div>
    </div>
</body>
</html>